server:
  port: 8088
  context-path: /

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 185766
    url: jdbc:mysql://localhost:3306/co?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
  jpa:
    show-sql: true

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: false
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: com.example.orienteering.typeHandler

weixin:
  jscode2sessionUrl: https://api.weixin.qq.com/sns/jscode2session
  getAccessTokenUrl: https://api.weixin.qq.com/cgi-bin/token
  getPhoneNumberUrl: https://api.weixin.qq.com/wxa/business/getuserphonenumber
  appid: wxde542db8d31a3359
  secret: b504947d6be0ab6a2cf67fc4cdb7c9ac